import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

/**
 * Thiên Kiếp Đài problem bank (judge-problems.json), generated by
 * scripts/build-judge-problems.py from reference solutions. Each problem is
 * one billthedev.com/docs/algorithms lesson told as a cultivation story.
 */

export const PARAM_TYPES = ['int', 'int[]', 'string', 'string[]', 'bool'] as const;
export const RETURN_TYPES = [...PARAM_TYPES, 'string[][]'] as const;
export type ParamType = (typeof PARAM_TYPES)[number];
export type ReturnType = (typeof RETURN_TYPES)[number];

const genSchema = z.union([
  z.object({
    $gen: z.literal('ints'),
    seed: z.number().int(),
    n: z.number().int(),
    lo: z.number().int(),
    hi: z.number().int(),
  }),
  z.object({
    $gen: z.literal('sorted'),
    seed: z.number().int(),
    n: z.number().int(),
    start: z.number().int(),
    gap: z.number().int(),
  }),
  z.object({
    $gen: z.literal('str'),
    seed: z.number().int(),
    n: z.number().int(),
    alphabet: z.string().min(1),
  }),
  z.object({
    $gen: z.literal('grid'),
    seed: z.number().int(),
    rows: z.number().int(),
    cols: z.number().int(),
    alphabet: z.string().min(1),
  }),
]);
export type GenSpec = z.infer<typeof genSchema>;
export type ArgValue = unknown;

const caseSchema = z.object({ a: z.array(z.unknown()), e: z.unknown() });

const problemSchema = z.object({
  slug: z.string().min(1),
  title: z.string().min(1),
  difficulty: z.enum(['easy', 'medium', 'hard']),
  docs: z.string().startsWith('/docs/algorithms/'),
  fn: z.string().regex(/^[a-z][a-z_]*$/),
  params: z.array(z.object({ name: z.string().min(1), type: z.enum(PARAM_TYPES) })).min(1),
  returns: z.enum(RETURN_TYPES),
  compare: z.enum(['exact', 'sorted', 'groups']),
  story: z.string().min(1),
  statement: z.string().min(1),
  constraints: z.string().min(1),
  examples: z.array(caseSchema).min(1),
  tests: z.array(caseSchema).min(8),
});

const bankSchema = z.object({
  $schema: z.string(),
  checksumOver: z.number().int().positive(),
  problems: z.array(problemSchema).min(1),
});

export type JudgeProblem = z.infer<typeof problemSchema>;
export type JudgeCase = z.infer<typeof caseSchema>;

export function isGen(v: unknown): v is GenSpec {
  return genSchema.safeParse(v).success;
}

let cached: { checksumOver: number; problems: JudgeProblem[] } | null = null;

export function loadJudgeBank(): { checksumOver: number; problems: JudgeProblem[] } {
  if (cached) return cached;
  const raw = readFileSync(
    fileURLToPath(new URL('./judge-problems.json', import.meta.url)),
    'utf-8',
  );
  const bank = bankSchema.parse(JSON.parse(raw));
  for (const p of bank.problems) {
    for (const c of [...p.examples, ...p.tests]) {
      if (c.a.length !== p.params.length)
        throw new Error(`judge: ${p.slug} has a case with wrong arity`);
    }
  }
  cached = { checksumOver: bank.checksumOver, problems: bank.problems };
  return cached;
}

export function judgeProblem(slug: string): JudgeProblem | null {
  return loadJudgeBank().problems.find((p) => p.slug === slug) ?? null;
}

/** snake_case → camelCase (JS) / PascalCase (C#). */
export const jsName = (fn: string): string =>
  fn.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
export const csName = (fn: string): string => {
  const c = jsName(fn);
  return c.charAt(0).toUpperCase() + c.slice(1);
};
